version: '3' # Which version of Docker Compose to use
services:
  42-x11:
    image: fourtytwo
    entrypoint: bash -c "./42"
    environment:
      - DISPLAY=host.docker.internal:0

  42-vnc:
    image: fourtytwo 
    environment:
      - DISPLAY=:20
      - LISTENPORT=16920
      - VNCPORT=15920
    ports:
      - 15920:15920
      - 16920:16920
